lsi: false
host: 0.0.0.0
source: .
exclude:
  - src
  - "*.ai"
  - "*.psd"
  - "*.sh"
  - "*.log"
  - "README.md"
  - "bower.json"
  - "package.json"
  - functions
include:
  - ".htaccess"
  - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
  - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map"
  - "node_modules/cookieconsent/build/cookieconsent.min.css"
  - "node_modules/cookieconsent/build/cookieconsent.min.js"
highlighter: rouge
incremental: true
sass:
  style: compressed
  sourcemap: always
  load_paths:
    - _css
    - node_modules
picture:
  source: "_assets/"
  output: "assets"
pagination:
  enabled: true
  limit: 0
  per_page: 12
  sort_field: 'date'
  sort_reverse: true
#This is the public test api key and can be publicly shared consequence-free
# It will be overriden by further "_deploy.yml" file during deployment.
snipcart_api_key: ZmMyNTVlYzYtMGJmMS00NDE4LThjYTktOTE0YmFlYjZmZmZkNjM2MTQzNjEyNzYwNDkzMDM2
permalink: /:path

collections:
  posts:
    output: true
    permalink: /:categories/posts/:title
  content_dev:
    permalink: /dev/:path
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the projec
      type: "pages"
    values:
      layout: "index"
# Posts layout
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "fr/store"
    values:
      layout: "store_item"
  -
    scope:
      path: "en/store"
    values:
      layout: "store_item"
  -
    scope:
      path: ""
      type: "content_dev"
    values:
      domain: "/dev"
      layout: "dev_page"
#new lang set for jekyll >3.1
  -
    scope:
      path: "_content_dev/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_dev/en"
    values:
      lang: "en"
  -
    scope:
      path: "static/**/*.pdf"
    values:
      sitemap: false




# most default config is made in make_collections plugin because this mechanism is too restrictive
