lsi: false
source: .
exclude:
  - node_modules
  - src
  - "*.ai"
  - "*.psd"
  - "*.sh"
  - "Gemfile*"
  - "README.md"
  - "bower.json"
  - "package.json"
  - "build/zopflipng"
  - "build/static"
highlighter: rouge
incremental: true
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: _css
  style: :compressed
  sourcemap: :true
#This is the public test api key and can be publicly shared consequence-free
# It will be overriden by further "_deploy.yml" file during deployment.
snipcart_api_key: ZmMyNTVlYzYtMGJmMS00NDE4LThjYTktOTE0YmFlYjZmZmZkNjM2MTQzNjEyNzYwNDkzMDM2
collections:
  content_main:
    permalink: /:path
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "index"
#new lang set for jekyll >3.1
  -
    scope:
      path: "_content_main/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_main/en"
    values:
      lang: "en"
# Posts layout
  -
    scope:
      path: "_content_main/fr/posts"
    values:
      layout: "post"
  -
    scope:
      path: "_content_main/en/posts"
    values:
      layout: "post"
