collections:
  content_dev:
    permalink: /:path
    output: true
  content_main:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "content_dev"
    values:
      layout: "dev_site"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "index"
  -
    scope:
      path: ""
      type: "content_dev"
    values:
      domain: "/dev"
      layout: "dev_site"
#new lang set for jekyll >3.1
  -
    scope:
      path: "_content_dev/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_dev/en"
    values:
      lang: "en"
