lsi: false
host: 0.0.0.0
source: .
exclude:
  - src
  - "*.ai"
  - "*.psd"
  - "*.sh"
  - "Gemfile*"
  - "README.md"
  - "bower.json"
  - "package.json"
  - "build/zopflipng"
  - "build/phantomjs"
  - "build/static"
highlighter: rouge
incremental: true
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-inline-svg
  - jekyll-paginate-v2
sass:
  style: compressed
  sourcemap: true
  load_paths:
    - _css
    - node_modules
pagination:
  enabled: true
  limit: 0
  per_page: 12
  sort_field: 'date'
  sort_reverse: true
#This is the public test api key and can be publicly shared consequence-free
# It will be overriden by further "_deploy.yml" file during deployment.
snipcart_api_key: ZmMyNTVlYzYtMGJmMS00NDE4LThjYTktOTE0YmFlYjZmZmZkNjM2MTQzNjEyNzYwNDkzMDM2
permalink: /:path
collections:
  posts:
    output: true
    permalink: /:categories/posts/:title
  content_dev:
    permalink: /dev/:path
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the projec
      type: "pages"
    values:
      layout: "index"
# Posts layout
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "fr/store"
    values:
      layout: "store_item"
  -
    scope:
      path: "en/store"
    values:
      layout: "store_item"
  -
    scope:
      path: ""
      type: "content_dev"
    values:
      domain: "/dev"
      layout: "dev_page"
#new lang set for jekyll >3.1
  -
    scope:
      path: "_content_dev/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_dev/en"
    values:
      lang: "en"

# most default config is made in make_collections plugin because this mechanism is too restrictive
