lsi: false
source: .
exclude:
  - node_modules
  - src
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: _css
  style: :compressed
  sourcemap: :true

collections:
  content_dev:
    permalink: /dev/:path
    output: true
  content_main:
    permalink: /:path
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "index"
  -
    scope:
      path: ""
      type: "content_dev"
    values:
      domain: "/dev"
      layout: "dev_site"

  #legacy lang set for old jekyll
  -
    scope:
      path: "dev/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "dev/en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
  -
    scope:
      path: "en"
    values:
      lang: "en"
#new lang set for jekyll >3.1
  -
    scope:
      path: "_content_dev/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_dev/en"
    values:
      lang: "en"
  -
    scope:
      path: "_content_main/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_content_main/en"
    values:
      lang: "en"
# Posts layout
  -
    scope:
      path: "_content_main/fr/posts"
    values:
      layout: "post"
  -
    scope:
      path: "_content_main/en/posts"
    values:
      layout: "post"
