name: Deploy functions
on:
  push:
    branches:
      - master
    paths:
     - "functions/**"
     - ".github/workflows/functions.yml"
env:
  NODE_VERSION: 12
defaults:
  run:
    working-directory: functions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}-
      - name: install base dependencies
        working-directory: ./
        run: npm i --global firebase-tools@$(node -e 'process.stdout.write(require("./package.json").devDependencies["firebase-tools"])')
      - name: install functions dependencies
        run: npm ci
      - name: run eslint
        run: npm run lint
      - name: test functions
        run: npm test
      - name: deploy
        working-directory: ./
        env:
          # it is revoked if it has not been used for 6 months
          # Generate a new one from command line using `firebase login:ci` and update it on Github
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npx firebase --token "$FIREBASE_TOKEN" deploy --only functions
