name: Deploy functions
on:
  push:
    branches:
      - master
    paths:
     - "functions/**"
     - ".github/workflows/functions.yml"
env:
  NODE_VERSION: 16
  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/.serviceAccount.json
defaults:
  run:
    working-directory: functions
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}-
      - name: export google credentials to a file
        env:
          FIREBASE_ACCOUNT: "${{ secrets.FIREBASE_ACCOUNT_KEY }}"
        run: echo "$FIREBASE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
      - name: install base dependencies
        working-directory: ./
        run: npm i --global firebase-tools@latest
      - name: install functions dependencies
        run: npm ci
      - name: run eslint
        run: npm run lint
      - name: test functions
        run: npm test
      - name: deploy
        working-directory: ./
        run: |
          npx firebase deploy --only functions
